package com.dblhargrove.database.Assets

import kotlinx.serialization.Serializable

@Serializable
data class CompanyProfile(
    val symbol: String,
    val price: Double,
    val beta: Double?,
    val volAvg: Int?,
    val mktCap: Long?,
    val lastDiv: Double?,
    val range: String?,
    val changes: Double?,
    val companyName: String?,
    val currency: String?,
    val exchange: String?,
    val industry: String?,
    val description: String?,
    val ceo: String?,
    val sector: String?,
    val phone: String?,
    val address: String?,
    val ipoDate: String?,
    val isEtf: Boolean?,
    val isActivelyTrading: Boolean?,
)

val sampleCompanyProfiles = listOf(
    CompanyProfile(
        symbol = "AAPL",
        price = 175.50,
        beta = 1.2,
        volAvg = 50000000,
        mktCap = 2_800_000_000_000,
        lastDiv = 0.22,
        range = "150-180",
        changes = 2.5,
        companyName = "Apple Inc.",
        currency = "USD",
        exchange = "NASDAQ",
        industry = "Technology",
        description = "Apple Inc. designs, manufactures, and markets smartphones, tablets, and personal computers.",
        ceo = "Tim Cook",
        sector = "Technology",
        phone = "+1 800-275-2273",
        address = "One Apple Park Way, Cupertino, CA",
        ipoDate = "1980-12-12",
        isEtf = false,
        isActivelyTrading = true
    ),
    CompanyProfile(
        symbol = "TSLA",
        price = 245.30,
        beta = 2.0,
        volAvg = 30000000,
        mktCap = 780_000_000_000,
        lastDiv = null,
        range = "200-280",
        changes = -3.2,
        companyName = "Tesla Inc.",
        currency = "USD",
        exchange = "NASDAQ",
        industry = "Automotive",
        description = "Tesla Inc. designs, manufactures, and sells electric vehicles and energy storage systems.",
        ceo = "Elon Musk",
        sector = "Consumer Discretionary",
        phone = "+1 650-681-5000",
        address = "3500 Deer Creek Road, Palo Alto, CA",
        ipoDate = "2010-06-29",
        isEtf = false,
        isActivelyTrading = true
    ),
    CompanyProfile(
        symbol = "GOOGL",
        price = 2850.75,
        beta = 1.1,
        volAvg = 12000000,
        mktCap = 1_800_000_000_000,
        lastDiv = 0.0,
        range = "2600-3000",
        changes = 5.1,
        companyName = "Alphabet Inc.",
        currency = "USD",
        exchange = "NASDAQ",
        industry = "Technology",
        description = "Alphabet Inc. is the parent company of Google, specializing in internet services and AI.",
        ceo = "Sundar Pichai",
        sector = "Technology",
        phone = "+1 650-253-0000",
        address = "1600 Amphitheatre Parkway, Mountain View, CA",
        ipoDate = "2004-08-19",
        isEtf = false,
        isActivelyTrading = true
    ),
    CompanyProfile(
        symbol = "AMZN",
        price = 3300.50,
        beta = 1.3,
        volAvg = 25000000,
        mktCap = 1_600_000_000_000,
        lastDiv = 0.0,
        range = "3100-3500",
        changes = -10.2,
        companyName = "Amazon.com Inc.",
        currency = "USD",
        exchange = "NASDAQ",
        industry = "E-commerce",
        description = "Amazon.com Inc. engages in online retail, cloud computing, and artificial intelligence services.",
        ceo = "Andy Jassy",
        sector = "Consumer Discretionary",
        phone = "+1 206-266-1000",
        address = "410 Terry Ave N, Seattle, WA",
        ipoDate = "1997-05-15",
        isEtf = false,
        isActivelyTrading = true
    )
)
